// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_german_winterdark_masked");
	self attach("xmodel/head_german_normandy_eric", "", true);
	if(level.ex_hatmodels)
	{
		hatmodel = character\mp_hatmodels::randomHatModel(character\mp_hatmodels::mp_german_winter());
		if(hatmodel != "") self.hatModel = hatmodel;
	}
	else self.hatModel = "xmodel/helmet_german_winter_dark";
	if(isDefined(self.hatModel)) self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_german_winter");
}

precache()
{
	[[level.ex_PrecacheModel]]("xmodel/playerbody_german_winterdark_masked");
	[[level.ex_PrecacheModel]]("xmodel/head_german_normandy_eric");
	if(!level.ex_hatmodels) [[level.ex_PrecacheModel]]("xmodel/helmet_german_winter_dark");
	[[level.ex_PrecacheModel]]("xmodel/viewmodel_hands_german_winter");
}
