// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_germann_diana_medic");
	self setViewmodel("xmodel/viewmodel_hands_russian");
}

precache()
{
	[[level.ex_PrecacheModel]]("xmodel/character_germann_diana_medic");
	[[level.ex_PrecacheModel]]("xmodel/viewmodel_hands_russian");
}
